admin/controllers/pages/page_options.json, admin/controllers/pages/views/edit/model.php, admin/controllers/pages/views/edit/view.php, admin/controllers/pages/views/save/model.php, admin/controllers/settings/views/info/view.php, admin/controllers/settings/views/updates/model.php, admin/controllers/settings/views/updates/view.php, core/fields/Field_Textarea.php, core/page.php, installer/schema.sql
Added page options functionality and updated installer schema. Checks for correct column existing added to update controller in admin.
=> Pageoptions

admin/controllers/content/views/all/model.php, admin/controllers/content/views/all/view.php, admin/forms/general_options.json, core/cms.php, core/configuration.php, core/content.php
Content pagination working fine 💯
=> Pagination

admin/controllers/categories/controller.php, admin/controllers/categories/views/all/model.php, admin/controllers/categories/views/all/view.php, admin/controllers/categories/views/edit/model.php, admin/controllers/categories/views/edit/required_fields_form.json, admin/controllers/categories/views/edit/view.php, admin/controllers/content/views/all/view.php, admin/controllers/content/views/edit/model.php, admin/controllers/content/views/edit/required_fields_form.json, admin/controllers/tags/views/edit/required_fields_form.json, admin/controllers/tags/views/show/model.php, admin/controllers/tags/views/show/view.php, admin/templates/clean/index.php, core/category.php, core/content.php, core/db.php, core/fields/Field_Category.php, core/tag.php
Hey categories are cool - please add them!
=> Contentcategories

admin/controllers/images/controller.php, admin/controllers/images/views/show/model.php, admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/view.php, admin/controllers/images/views/uploadv2/model.php, admin/controllers/images/views/uploadv2/view.php, admin/templates/clean/css/layout.css, core/content.php, core/file.php
New JS uploader - no more temp upload folder nonsense
=> Newuploader

admin/controllers/content/views/all/model.php, core/content.php
=> fix admin pagination

admin/controllers/images/views/show/model.php, admin/controllers/images/views/show/script.js, admin/controllers/images/views/uploadv2/model.php, core/controllers/image/controller.php, core/file.php
Allows the CMS to handle .webp images.
=> Support for .webp images

admin/controllers/images/views/show/model.php, admin/controllers/images/views/show/script.js, admin/controllers/images/views/uploadv2/model.php, core/controllers/image/controller.php, core/file.php
=> refactor support for svg's, add support for gifs

admin/admin_config.php, admin/templates/clean/index.php, core/access.php, core/cms.php
=> implement access control

core/fields/Field_Select.php
=> support slim select option in select json

admin/templates/clean/css/layout.css, core/fields/Field_Rich.php
Modifies "IMG ATTRIB" functionality in text editor to display modal to add/update figure caption. If caption already present data is moved into modal to be modified.
Note: Adds support for "FL", "FR", and "FC" of captioned image. Note that "FL" leads to a slightly weird layout in editor, though this was previous behavior with image when no caption present. This should close #137 but may need another issue opened to clean up text editor layout.
=> Adds editor figure/captions working with float.

core/fields/Field_Textarea.php
=> Bug fix for required textarea field.

core/cms.php
=> add uripath to javascript

admin/templates/clean/css/darkmode.css, admin/templates/clean/index.php
=> add initial darkmode support

admin/templates/clean/css/darkmode.css
see title
fixes https://github.com/HoltBosse/Alba/issues/159
=> style buttons and slim selects

core/content.php
see title
redo of https://github.com/HoltBosse/Alba/pull/144
=> change get all content to be run by new content_search

admin/controllers/users/views/default/model.php, admin/controllers/users/views/default/view.php, admin/templates/clean/css/dashboard.css, admin/templates/clean/css/layout.css, admin/templates/clean/index.php, core/user.php, core/users_search.php
- New Users_Search class implemented, similar to content search class. 
- Better UI for filtering users in backend.
@workaj - you can test here, login with holtbosse google: https://cmstest.bobmitch.com/admin
=> user filtering and pagination

admin/templates/clean/css/darkmode.css
=> style: make navmenu elements arrow match text color

core/mail.php
* feat: Adds mail attachments. Mail send returns true on successful send, false on exception.
=> Mail modifications (#177)

admin/templates/clean/css/darkmode.css
=> bug: make single item selects darkmode, make multiple selected items same blue as buttons

core/fields/Field_Image.php
- escape key dismisses modal
- clear search field button added
- ui element container now position sticky
- small layout improvements
=> feat: small media selector qol changes

admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/view.php
Adds file input button so mobile users can upload images too!
(or people who just prefer that interface too I guess)
=> feat: reg. img upload not just dragdrop

.gitignore
=> feat: ignore non default templates

core/cms.php
This reverts commit ce9f1174cc554a3b272c0beaa765bb156a75d266.
done since its full of bugs
fixes https://github.com/HoltBosse/Alba/issues/198
=> Revert "feat: better homepage 404 testing"

core/db.php
=> feat: set pdo obj mode so that you dont get spammed with warnings when debug is turned on

core/cms.php
fixes https://github.com/HoltBosse/Alba/issues/209
see title
=> feat: add http error code in raise error function

admin/templates/clean/css/darkmode.css, admin/templates/clean/login.php
simple pr. messed around with the white outline around google login buttons, wasnt able to figure that out as it doesnt seem to be set anywhere....
=> feat: add darkmode css to admin login page

admin/templates/clean/css/darkmode.css
should make @ehalder happy .... maybe
=> new darkmode for admin template

.gitignore, admin/controllers/content/views/all/view.php, core/content_search.php
Plugin for testing below - simulates existing content title search for basic articles only.
Note: Not all 'add_action's are needed besides the render_controls and one other data manipulation action, but are present here for copy/pasting when writing more complex plugins.
---
Plugin folder: custom_content_search_controls
---
plugin_config.json
```json
{
"title":"Custom Content Search",
"location":"custom_content_search_controls",
"id":"ccsc",
"description":"Render search fields for custom content",
"version":"1.0",
"author":"Bob Mitchell",
"website":"https://holtbosse.com",
"fields":[
]
}
```
plugin_class.php
```php
<?php
defined('CMSPATH') or die; // prevent unauthorized access
class Plugin_custom_content_search_controls extends Plugin {
public function init() { …
```
=> Contentsearchhooks

.github/scripts/build.sh, .github/workflows/build_release.yml
=> feat: first attempt at ci

core/fields/Field_Rich.php
edit something on cmstest.bobmitch.com if you want to test
=> feat: remove styles during paste always

admin/templates/clean/css/darkmode.css
=> feat: tweak blue to be better

admin/templates/clean/css/darkmode.css
=> feat: fix menu darkmode bugs

admin/controllers/images/views/show/model.php, admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/view.php, admin/controllers/images/views/uploadv2/model.php, admin/templates/clean/index.php, core/fields/Field_Image.php, core/image.php
see title. currently wip
current todos:
=> integrate basic image editor into the cms

htaccess.txt
=> feat: block dev stuff in htaccess

core/cms.php
This may be bloat, but I think it could be helpful. Was useful at times when I was working on layout, especially because I didn't want whatever I was `CMS::pprint_r`ing vomited out into my layout.
What do you guys think @workaj  @bobmitch?
=> feat: adds console log as less obtrusive pprint_r.

.gitignore, admin/controllers/users/views/save/model.php, core/user.php, plugins/core_user_verify/plugin_class.php, plugins/core_user_verify/plugin_config.json
just plain works. no frills currently. all it requires is that you have email set up and that you hook it and pass it the right post params
todo:
=> user verification

core/fields/Field_FilePicker.php
see title
improves @bobmitch code
=> feat: add file or folder selecter

plugins/core_user_verify/plugin_class.php, plugins/core_user_verify/plugin_config.json
Customizable logo (defaults to set image, admin logo, then alba logo), link color, and CTA color.
=> feat: adds fancier user verification email

core/user.php, plugins/core_user_verify/plugin_class.php
see title
fixes https://github.com/HoltBosse/Alba/issues/247
=> bug: fix old users edited in admin getting a registration email again as well as a user class bug

core/fields/Field_Text.php, core/input.php
see title
adds support for this novel feature called decimals
=> feat: add supports for floats

admin/controllers/content/views/action/model.php, admin/controllers/content/views/all/view.php, admin/templates/clean/css/darkmode.css
see title
demo from controllers custom_fields.json
```json
"states":[
{
"name":"purgatory",
"color":"yellow",
"state": 2
}
],
```
=> adds content states support to the gui

admin/controllers/content/views/edit/model.php
fixes https://github.com/HoltBosse/Alba/issues/254
ready for review
=> feat: add support for custom states in content required fields

core/fields/Field_Rich.php
Fix strange plaintext string pasting bug that Anthony could not replicate. :)
=> Fixeditorpaste

admin/controllers/pages/views/save/model.php
=> bug: fix https://github.com/HoltBosse/Alba/issues/173

admin/templates/clean/css/dashboard.css, core/fields/Field_Allcontentselector.php, core/fields/Field_Category.php, core/fields/Field_Checkbox.php, core/fields/Field_ContentPicker.php, core/fields/Field_ContentPickerOrdered.php, core/fields/Field_ContentTypeselector.php, core/fields/Field_Contentselector.php, core/fields/Field_FilePicker.php, core/fields/Field_FileUploader.php, core/fields/Field_HTML.php, core/fields/Field_Image.php, core/fields/Field_Pageselector.php, core/fields/Field_Positionselect.php, core/fields/Field_RecaptchaV2.php, core/fields/Field_Repeatable.php, core/fields/Field_Rich.php, core/fields/Field_Select.php, core/fields/Field_TagMultiple.php, core/fields/Field_TagParent.php, core/fields/Field_TagSingle.php, core/fields/Field_Templateselect.php, core/fields/Field_Text.php, core/fields/Field_Textarea.php, core/fields/Field_Tree.php, core/fields/Field_UserGroupsMultiple.php, core/form.php, testform.json
Non-breaking addition that allows fields to be displayed / hidden based on values of other elements on screen.
For now only equivalence comparison implemented (most common use case).
e.g. 
```json
{
"type":"Checkbox",
"id":"logic3",
"name":"logic3",
"label":"Double PDF?",
"logic":[
[
{
"field": "logic1",
"test": "==",
"value": "pdf"
}
]
]
```
=> Fieldlogic

admin/controllers/pages/views/save/model.php
nothing to see here at all. totally not fixing my previous buggy pr
=> bug: only check if a page exists if its a new one

core/fields/Field_Repeatable.php
=> feat: allow repeatables on page view selection

core/fields/Field_Repeatable.php
=> feat: repeatables suck, improvements

core/fields/Field_Select.php
=> bug: fix highly overrated lack of loading saved data when using multiselect

core/fields/Field_TagMultiple.php
=> feat: show full tag path

admin/templates/clean/css/darkmode.css, admin/templates/clean/css/dashboard.css, admin/templates/clean/js/script.js
see title. ~~currently wip~~
EDIT: now ready for review
=> mobile tweaks and fixes to make the cms ..... more usable on mobile

admin/controllers/categories/views/action/model.php, admin/controllers/categories/views/action/view.php, core/controller.php
=> feat: add novel concept of actions for categories

core/fields/Field_Rich.php, core/form.php
Rich field now repeatable friendly. Josh tested to his satisfaction.
=> Richrepeatable

core/fields/Field_Rich.php
=> Feat: add tooltips to the rich editor

configTESTBACKUP.php, controllers/basic_article/views/blog/view.php, core/cms.php
Ostensibly done to fix my blog. ;)
But really this is something that's needed to allow any site that has a homepage that may need to consume URL params to work.
Rare on most of our sites, but necessary for a site that's a blog for example.
=> feat: homepage controller boolean + blog fix

core/content.php
As discussed to try and mitigate bizarre query slowdowns.
=> Remove sql unixtime

admin/logout.php
=> feat: account for uripath in logout

admin/admin_config.php, core/cms.php
=> feat: protect the admin home directory

admin/controllers/content/views/all/view.php, admin/templates/clean/css/darkmode.css
=> feat: better pagination

admin/controllers/widgets/views/edit/model.php, core/cms.php, core/widget.php, plugins/core_widget/plugin_class.php
=> Widget hooks

core/fields/Field_ContentPickerOrdered.php
=> feat: make contentpickerordered work with flatfields

controllers/basic_article/views/single/model.php
=> bug: fixed fetching markup

admin/controllers/content/views/new/new_controller_files/model.php, controllers/basic_article/views/blog/model.php, controllers/basic_article/views/blog/single.php, controllers/basic_article/views/blog/view.php, core/content_search.php
note that this does not fix pagination of the blog, that still remains to be fixed
=> chore: remove all left over instances of f_ and get blog controller working

core/cms.php
=> feat: improve default 404 page

core/cms.php
=> feat: head safety 101

core/fields/Field_Rich.php
adds small/superscript text support
=> feat: add small rich support

admin/controllers/home/controller.php
=> feat: allow custom views on home controller

admin/controllers/content/views/all/view.php, admin/controllers/content/views/api/model.php
=> Ordering fix

admin/controllers/content/views/check/model.php, core/content.php, core/content_search.php
probably not all of them, but ones found
=> sql escapes

.github/workflows/build_release.yml, admin/templates/clean/headlibraries.php, admin/templates/clean/index.php, core/cms.php, core/controller.php, plugins/core_frontend_editbutton/plugin_class.php, plugins/core_frontend_editbutton/style.css
this is a draft. try it out on my dev
```php
foreach($data->articles as $article) {
echo "
<div class='featured_card'>
<h5
class='title is-5 cfe_editable_content'
style='color: #aaa;'
data-contentid='$article->id'
data-contenttype='$article->content_type'
data-contentfield='title'
>
$article->title
</h5>
<p
class='cfe_editable_content'
data-contentid='$article->id'
data-contenttype='$article->content_type'
data-contentfield='og_description'
>
$article->og_description
</p>
</div>
";
}
```
sample code for making a content item editable from the front end
=> improve the ability to edit content from the front end

admin/controllers/users/views/default/view.php
continuation of https://github.com/HoltBosse/Alba/pull/298, but for users
=> better user pagination to be inline with improved content pagination

admin/controllers/widgets/views/show/model.php
fixes https://github.com/HoltBosse/Alba/issues/314
for bonus points spot the security hole
=> flipping widget ordering, clean up code

admin/controllers/users/controller.php
=> bug: fix issue requiring custom user fields

admin/controllers/users/views/edit/view.php, admin/controllers/users/views/save/model.php
=> Userfieldsfixes

admin/controllers/users/views/save/model.php, core/controllers/image/controller.php, core/fields/Field_Image.php
=> Image field tag filtering

core/field.php
Will fix some crappy errors when saving repeatables, kinda needed for VAL right now.
=> fix: repeatable text fields validation

.github/workflows/phpstan.yml
adds a disabled basic phpstan test for now
=> Phpstan GitHub actions

core/fields/Field_Antispam.php
Targets single field for specific checks.
Though about making a config json option for targeting multiple fields with multiple different config combos, but for simplicity for now, easier to just use multiple anti-spam fields for each field being tested.
=> Antispamfield

core/fields/Field_Contentselector.php
see title
....yes, another one...... also yes this field should eventually be rewritten with proper oop to extend off the field select
=> bug: wrap table name so that it doesnt error out on weird table names also use modern db call

admin/controllers/content/views/edit/view.php
=> feat: add encoding to content edit form so that files can be uploaded

core/cms.php
live caught this, no idea why my dev wasnt, but its fixed now regardless
=> fix some phpstan warnings we where ignoring in cms.php

core/content.php
Replace trash unique alias code.
Hide unique alias creation message from any non-admin situation.
=> feat: better unique alias and cleaner messaging

admin/controllers/audit/views/default/view.php, admin/controllers/content/views/all/view.php, admin/controllers/images/views/show/view.php, admin/controllers/redirects/views/all/view.php, admin/controllers/users/views/default/view.php, core/component.php, core/element.php
what it says on the tin
will help with stuff like https://github.com/HoltBosse/Alba/issues/203
in the future class will be expanded to contain other ui elements commonly used
=> feat: abstract pagination / deduplicate code

plugins/core_user_verify/plugin_class.php
fixes https://github.com/HoltBosse/Alba/issues/270
=> fix https://github.com/HoltBosse/Alba/issues/270

admin/controllers/categories/views/action/model.php, admin/controllers/tags/views/action/model.php
fixes https://github.com/HoltBosse/Alba/issues/348
=> fix https://github.com/HoltBosse/Alba/issues/348

admin/controllers/categories/views/edit/model.php, admin/controllers/categories/views/edit/view.php
fixes https://github.com/HoltBosse/Alba/issues/349
=> fix https://github.com/HoltBosse/Alba/issues/349

core/fields/Field_Contentselector.php
Maybe add a config attribute to allow just showing id/default value vs doing lookup?
=> feat: friendly contentselector value

admin/controllers/content/views/all/view.php, admin/controllers/pages/views/default/view.php, admin/controllers/plugins/views/show/view.php, admin/controllers/widgets/views/show/view.php, core/component.php
=> feat: abstract addon button group

core/fields/Field_Rich.php
Insert image in rich editor currently broken on flat, this is an attempt to get it working.
Will need to attempt a better DRY approach that both this and the Image field can both use.
=> fix: rich editor image insertion

core/fields/Field_Contentselector.php
fixes issue on val features noted by BB
=> fix: get content type correctly

htaccess.txt
=> feat: prevent driveby sniffing, external iframing of site

admin/controllers/pages/views/edit/view.php, core/page.php
Added a hidden input to pass the state through the POST variable and adjusted the state check rule when loading from post.
=> bug: fixed saving page sets to enabled every time

admin/controllers/settings/views/backups/model.php, core/mail.php, phpstan.neon
requires https://github.com/HoltBosse/Alba/pull/372 to be merged and then this rebased
=> Phpstan level 3

htaccess.txt
=> feat: block all composer related things from being web accessible

admin/controllers/images/views/uploadv2/model.php, core/fields/Field_Parsedown.php
=> markdown image upload

core/content.php
bug fix for table names that have a dash "-" instead of an underscore "_" between words in their name.
=> bug: bad table name bug fix

admin/templates/clean/index.php, admin/templates/clean/navigation.php, core/component.php
allows still using the default template while overriding the nav
admin config sample
```php
static $navigation = [
"system" => [
"type" => "disable", //should hide the menu
],
"users" => [
"type"=>"override_menu", //overrid of type menu
"menu"=>[
"label"=>"amazing users",
"links"=>[
"group 1 users"=>"/admin/link",
"group 2 users"=>"/admin/link",
]
]
],
"pages" => [
"type"=>"override_link", //override just as a top level
"link"=>[
"label"=>"amazing thing",
"url"=>"/admin/actualurl",
]
],
"newnavitem"=>[
"type"=>"addition_menu", //add a menu to the end
"menu"=>[
"label"=>"newnavitem",
"links"=>[
"group 1 newnavitem"=>"/admin/link",
"group 2 newnavitem"=>"/admin/link",
]
]
],
"newlinkthingnav"=>[
"type"=>"addition_link", //add a single link to the end
"link"=>[
"label"=>"amazing thing", …
```
=> Navigation overrides

admin/controllers/content/views/all/style.css, admin/controllers/content/views/all/view.php
=> bug: fix header getting out of alignment with content, additionally, fix grid item count to handle dynamic info

admin/controllers/categories/views/all/model.php, admin/controllers/categories/views/all/view.php, admin/controllers/content/views/all/script.js, admin/controllers/images/views/show/script.js
does the following
* replaces postajax usage with modern fetch
* leaves postajax functions for backwards compat for now
* removes ordering code from categories since it doesnt work and tags doesnt have that either
* fixes search code in categories.
* adds clear button to category search
arguably the last three arent really related to the core point of this pr, but i was there anyways
=> postajax removing

admin/controllers/content/views/edit/model.php, core/fields/Field_TagMultiple.php
=> bug: fix content type not applying to content tag picker

core/fields/Field_Image.php
=> feat: allow configuration of endpoints in image field

admin/controllers/images/views/show/image_upload_handling.js, admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/upload_space_handling.js, admin/controllers/images/views/show/view.php, core/fields/Field_Image.php, core/image.php
=> image field dialog uploader

admin/controllers/images/views/show/image_upload_handling.js, admin/controllers/images/views/show/script.js
note: main postajx function still exists in the template and gets loaded in every admin page. the one removed is just a duplicate
=> chore: convert raw xhr to fetch, get rid of duplicate postajax function

admin/controllers/images/views/show/image_upload_handling.js, admin/controllers/images/views/show/view.php, admin/controllers/images/views/uploadv2/model.php, core/controllers/image/controller.php, core/image.php
also contains a bugfix for multiple button clicks eventually failing
=> add the ability to add tags on image upload

admin/controllers/content/views/edit/view.php
closes https://github.com/HoltBosse/Alba/issues/401
a first stab at it
=> feat: implementation of warn before closing when a field is edited

templates/basic/layout.php
requires https://github.com/HoltBosse/Alba/pull/404 to be merged first, this rebased, and custom merge since i based it off the wrong branch
=> shove more warning spam under the correct config label

admin/controllers/content/views/edit/model.php, admin/controllers/content/views/edit/view.php, admin/controllers/users/views/edit/view.php, admin/controllers/users/views/save/model.php
=> feat: if a userwas searching in the admin backend, redirect them back to that on save

admin/controllers/content/views/all/script.js, admin/templates/clean/headlibraries.php
=> feat: remove insertafter object method and fix ordering when placing an item after

core/fields/Field_Image.php
Can be tested here: https://cmstest.bobmitch.com/admin/
=> feat: capture required hidden image field before submission

core/controllers/api/controller.php, core/fields/Field_Parsedown.php
does what it says on the tin, see commit titles
=> Parsedown field improvements

core/fields/Field_Select.php, core/fields/Field_TagMultiple.php, core/fields/Field_TagSingle.php
Will show, but not allow selection of Tags in TagMultiple field.
=> feat: disable unpublished tags in select options re: JN request

.github/workflows/build_release.yml, .github/workflows/phpstan.yml
see title
https://github.com/php-actions/phpstan/blob/master/README.md?plain=1#L48 is a lie, looks like its always using latest
=> pin version of phpstan used by ci

core/fields/Field_Image.php
=> chore: add class to media selector so it can be more easily styled without hacks. also fix media selector removal

core/fields/Field_ContentPicker.php
does what it says on the tin - slightly changes ordering of options, but 🤷
=> chore: oop selects

core/fields/Field_Contentselector.php
=> feat: allow configuration of ordering in content select

core/fields/Field_Image.php
fixes https://github.com/HoltBosse/Alba/issues/328
* adds alt and title attributes by default
* updates them when item is selected from media selector page
* uses alt and title attributes in cropper instead of hard coded values
=> Various image field fixes

admin/controllers/pages/views/edit/model.php, admin/controllers/pages/views/edit/view.php, core/widget.php, plugins/core_frontend_editbutton/plugin_class.php
Add filtering and previews for widget override method on page options.
=> Widgetpreviews

controllers/basic_article/sitemap.php, controllers/basic_article/views/blog/sitemap.php, core/cms.php, core/fakefiles/sitemap.xml.php
WARNING: for cms pages, it uses the pages last updated value, you may want to use the plugin hook in some site instances to override this field/make it driven by some piece of content on the page
=> add dynamically generated sitemap first stab

admin/controllers/content/views/edit/required_fields_form.json, core/fields/Field_Text.php
This reverts commit c74be3a9d582aff7f381b53c548d3d1eba73ff84.
=> Revert "feat: fix text field apostrophe catastrophe (#424)"

admin/controllers/content/views/all/model.php, admin/controllers/users/views/default/model.php, admin/controllers/users/views/default/view.php, core/content_search.php, core/users_search.php
=> chore: allow state checks lower than 0 in content and user search, also fix admin backend to make deleted user and content search work

admin/controllers/content/views/all/view.php, admin/controllers/pages/views/edit/view.php, admin/controllers/users/views/action/model.php, admin/controllers/users/views/default/view.php, admin/controllers/users/views/edit/core_user_fields.json, admin/controllers/users/views/edit/model.php, admin/controllers/users/views/edit/view.php, admin/controllers/users/views/save/model.php, admin/templates/clean/index.php, admin/templates/clean/login.php, core/actions.php, core/actions/Action_usercreate.php, core/actions/Action_userdelete.php, core/actions/Action_userlogin.php, core/actions/Action_userupdate.php, core/cms.php, core/fields/Field_Checkbox.php, core/fields/Field_ContentTypeselector.php, core/fields/Field_Pageselector.php, core/fields/Field_Select.php, core/fields/Field_Text.php, core/fields/Field_Tree.php, core/input.php, core/user.php, core/widget.php, plugins/core_frontend_editbutton/plugin_class.php
these commits are designed to be individually reviewable
=> Security user listing

admin/controllers/categories/views/action/model.php, admin/controllers/categories/views/all/view.php, admin/controllers/categories/views/edit/model.php, admin/controllers/categories/views/edit/required_fields_form.json, admin/controllers/categories/views/edit/view.php, admin/controllers/content/views/action/model.php, admin/controllers/content/views/all/view.php, admin/controllers/content/views/edit/model.php, admin/controllers/content/views/edit/required_fields_form.json, admin/controllers/content/views/edit/view.php, admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/view.php, admin/controllers/tags/views/action/model.php, admin/controllers/tags/views/edit/model.php, admin/controllers/tags/views/edit/required_fields_form.json, admin/controllers/tags/views/edit/view.php, admin/controllers/tags/views/show/view.php, admin/controllers/users/views/default/view.php, core/fields/Field_Select.php
=> chore: handle html as text properly through the cms

admin/controllers/content/views/edit/required_fields_form.json, admin/controllers/content/views/edit/script.js, admin/controllers/content/views/edit/style.css, admin/controllers/content/views/edit/view.php
fixes https://github.com/HoltBosse/Alba/issues/445
before:
after:
note: also makes mobile usable
=> Content editing required fields layouting

.github/workflows/codequality.yml, README.md, admin/controllers/content/views/all/script.js, admin/controllers/images/views/show/image_upload_handling.js, admin/controllers/images/views/show/script.js, admin/controllers/images/views/show/upload_space_handling.js, admin/js/menu_widget_admin.js, admin/templates/clean/js/script.js, biome.json
prettier in rust fyi. mostly used since it has a cli binary and i dont have to mess with npm
=> add biomejs

core/fields/Field_ContentPickerOrdered.php, core/fields/Field_PickerOrdered.php
as previously discussed
implements a base class for anyone to use, similar to select field
=> Content picker ordered refactor

admin/controllers/images/views/show/image_upload_handling.js
fixes https://github.com/HoltBosse/Alba/issues/452
=> fix uploaded required images being submit blocked

core/fields/Field_Select.php
=> feat: add bulma multiple class for multiple select

admin/templates/clean/navigation.php
=> feat: move media to under system in nav

admin/controllers/content/views/all/view.php, core/field.php, core/fields/Field_Antispam.php, core/fields/Field_Checkbox.php, core/fields/Field_ContentPickerOrdered.php, core/fields/Field_ContentTypeselector.php, core/fields/Field_FileUploader.php, core/fields/Field_HTML.php, core/fields/Field_Honeypot.php, core/fields/Field_Image.php, core/fields/Field_Pageselector.php, core/fields/Field_Parsedown.php, core/fields/Field_PickerOrdered.php, core/fields/Field_RecaptchaV2.php, core/fields/Field_Repeatable.php, core/fields/Field_Rich.php, core/fields/Field_Select.php, core/fields/Field_Tab.php, core/fields/Field_Text.php, core/fields/Field_Textarea.php, core/fields/Field_Tree.php, core/fields/Field_Turnstile.php, core/fields/Field_UserPicker.php
=> feat: clean up the fields load_from_config constructor

core/form.php
=> feat: verify that the form path is a string

admin/controllers/forms/views/submissions/model.php, admin/controllers/forms/views/submissions/view.php, core/fields/Field_ContentTypeselector.php, core/fields/Field_Image.php, core/fields/Field_Pageselector.php, core/fields/Field_RecaptchaV2.php, core/fields/Field_Select.php, core/fields/Field_Text.php, core/fields/Field_Textarea.php
=> feat: improve form submissions viewer

core/fields/Field_Image.php, core/fields/Field_Rich.php
show image dimension info in picker(s) - both rich editor and image field
=> feat: image size info in pickers

core/form.php
=> Form field logic basics

core/form.php
=> feat: refactor the field display logic

core/fields/Field_Select.php, core/form.php
=> Field select logic fixes and cleanup

core/configuration.php
=> bug: fix configuration form path

installer/schema.sql
=> chore: change type in sql

admin/controllers/pages/views/action/model.php, admin/controllers/pages/views/default/view.php, admin/controllers/pages/views/edit/view.php, admin/controllers/pages/views/save/model.php, core/cms.php, core/fields/Field_PageSelect.php, core/page.php
does what it says on the tin, fixes page select field as well
=> chore: make page title html char safe

admin/controllers/pages/views/edit/script.js
=> chore: stop spam

admin/controllers/settings/views/updates/model.php, admin/controllers/settings/views/updates/view.php, core/messages.php
adds server messages stored in the database, meant for not currently logged in users/etc
visit `/add_server_message` (you know which domain) to add some messages and log into admin
(contents of that file)
```php
Messages::save_message(1, "YOLO: " . uniqid());
Messages::save_message([1,2], "You RUINED schrodinger's message!!!: " . uniqid());
```
=> feat: add server messages

core/fields/Field_Repeatable.php
fixes https://github.com/HoltBosse/Alba/issues/468
=> fix add up and down to new repeatables

admin/controllers/audit/views/default/model.php, admin/controllers/audit/views/default/search_form.json, admin/controllers/audit/views/default/style.css, admin/controllers/audit/views/default/view.php
fixes https://github.com/HoltBosse/Alba/issues/462
=> feat: add filtering to audit log

core/fields/Field_Rich.php
=> rich editor logic changes + url editor client guardrails

admin/controllers/widgets/views/show/model.php, admin/controllers/widgets/views/show/search_form.json, admin/controllers/widgets/views/show/style.css, admin/controllers/widgets/views/show/view.php
fixes https://github.com/HoltBosse/Alba/issues/486
=> feat: add widget search

core/fields/Field_Rich.php
* Added checks to prevent alert when interacting with the code view toggle or raw editor. 
* Refactored the createanchor to use modal
=> Rich editor anchor modal

controllers/basic_article/custom_fields.json, core/fields/Field_Rich.php, core/fields/Field_Select.php
=> do the needful

core/cms.php
backslash in front of period not needed (didn't work at all)
=> feat: ignore git related urls in redirect creation

core/fields/Field_Turnstile.php, htaccess.txt
see title
for turnstile logging
want to see if its builtin cms error, or cloudflare returning one of https://developers.cloudflare.com/turnstile/get-started/server-side-validation/#error-codes
=> htaccess changes + turnstile debug aids

core/fields/Field_Image.php, core/fields/Field_Rich.php, core/js/media_selector.js
Format the media selector logic into a reusable module. Also has some minor refactoring for better readability and maintainability of the code.
* Replaced the inline implementation of the media selector in `Field_Image.php` with the reusable `openMediaSelector` function. 
* Updated the image insertion logic in the rich text editor `Field_Rich.php` to use `openMediaSelector` function.
* Updated the `<script>` tags to be able to use modules.
=> Media Selector Module

core/fields/Field_Checkbox.php, core/form.php
Open to alternatives, this is my best stab at it
=> feat: fix checkbox form class logic

core/js/download_table_as_csv.js
=> feat: add js module for converting table to csv

admin/controllers/audit/controller.php, admin/controllers/audit/views/more/model.php, admin/controllers/categories/controller.php, admin/controllers/categories/views/all/model.php, admin/controllers/categories/views/edit/model.php, admin/controllers/content/controller.php, admin/controllers/content/views/all/model.php, admin/controllers/content/views/order/model.php, admin/controllers/forms/controller.php, admin/controllers/forms/views/submissions/model.php, admin/controllers/home/controller.php, admin/controllers/images/controller.php, admin/controllers/images/views/show/model.php, admin/controllers/pages/controller.php, admin/controllers/plugins/controller.php, admin/controllers/plugins/views/default/model.php, admin/controllers/plugins/views/default/view.php, admin/controllers/plugins/views/show/model.php, admin/controllers/redirects/controller.php, admin/controllers/settings/controller.php, admin/controllers/tags/controller.php, admin/controllers/users/controller.php, admin/controllers/users/views/edit/model.php, admin/controllers/widgets/controller.php, admin/templates/clean/index.php
=> feat: start 404ing on bad pages rather than error or nothing

composer.json
prevents files from being overwritten in composer install is run again.
=> Composer install upgrades

core/fields/Field_Text.php, core/input.php
=> bug: handle htmlspecialchars consistently accross different php versions

admin/controllers/categories/views/edit/view.php, admin/controllers/content/views/edit/view.php, admin/controllers/pages/views/edit/view.php, admin/controllers/plugins/views/edit/view.php, admin/controllers/redirects/views/edit/view.php, admin/controllers/tags/views/edit/view.php, admin/controllers/users/views/edit/view.php, admin/controllers/widgets/views/edit/view.php, admin/templates/clean/css/darkmode.css, admin/templates/clean/css/layout.css, core/component.php
=> feat: make control bar a component, add to user page, and fix back not working

.github/scripts/build.sh, admin/controllers/pages/views/edit/view.php, templates/basic/style.css
* make it actually blank
* put templates in final export
* always show page details in page edit mode like content
=> basic template tweaks

core/fields/Field_Rich.php
=> chore: make editor work in repeatables

admin/controllers/pages/views/edit/view.php
fixes #514 
rearranges deck chairs on the titanic
=> feat: make view options in admin page configure full width

admin/controllers/pages/views/edit/view.php, admin/controllers/pages/views/save/model.php
=> feat: implement quicksave on admin pages

admin/controllers/pages/views/default/view.php, core/js/admin_row.js
=> chore: make admin alias link clickable and fix up row selecting

admin/controllers/pages/views/save/model.php, core/category.php, core/form.php, core/tag.php, plugins/core_frontend_editbutton/plugin_class.php
=> feat: use jsonserializable interface for form class

admin/controllers/settings/views/updates/model.php, admin/controllers/settings/views/updates/view.php
does what it says on the tin. this basically wasnt being used, conflict with keeping in sites in git, and wont work at all come #526
=> feat: remove admin update

admin/controllers/content/controller.php, admin/controllers/images/views/api/model.php, admin/controllers/images/views/uploadv2/model.php, admin/controllers/pages/views/action/model.php, admin/controllers/plugins/views/edit/model.php, core/category.php, core/cms.php, core/configuration.php, core/content.php, core/controllers/image/controller.php, core/page.php, core/plugin.php, core/tag.php, core/template.php, core/user.php, core/widget.php, widgets/crowdriff/widget_class.php
fixes https://github.com/HoltBosse/Alba/issues/525
if your using pdo outside of the cms itself..... well that deserves to break and get fixed
=> feat: use db class everywhere and toss cms pdo object

core/fields/Field_Repeatable.php, core/fields/Field_Rich.php
=> feat: add new rich editor

admin/templates/clean/css/dashboard.css
=> feat: view transitions

admin/templates/clean/headlibraries.php
honestly if your still using this instead of the fetch api........... why? just convert it already
=> trashfire: toss postajax

admin/controllers/images/views/show/view.php, core/fields/Field_Image.php
=> chore: fix cropper css being included multiple times

admin/controllers/categories/views/all/view.php, admin/controllers/content/views/all/style.css, admin/controllers/content/views/all/view.php, admin/controllers/pages/views/default/view.php, admin/controllers/plugins/views/show/view.php, admin/controllers/redirects/views/all/style.css, admin/controllers/redirects/views/all/view.php, admin/controllers/tags/views/show/view.php, admin/controllers/users/views/default/view.php, admin/controllers/widgets/views/show/view.php, core/component.php
=> feat: unify state toggle in components class

admin/controllers/images/views/show/view.php, admin/templates/clean/css/darkmode.css, admin/templates/clean/css/layout.css, admin/templates/clean/headlibraries.php, core/fields/Field_Image.php, core/fields/Field_Select.php, core/js/image_uploading.js
=> chore: apply 5 years worth of slimselect updates

core/fields/Field_TagMultiple.php, core/fields/Field_TagParent.php, core/fields/Field_TagSingle.php
* dev has to use software
* dev gets annoyed
* dev fixes software
bring the formatting of tag multiple to all tag fields because otherwise you have no clue what the parent tag is
=> chore: unify tag fields

src/admin/controllers/pages/views/default/view.php
fixes https://github.com/HoltBosse/Alba/issues/33
4 years later
=> feat: show full path in admin pages list view

bin/alba, bin/sql/mariadb/form_submissions.sql
fixes https://github.com/HoltBosse/Alba/issues/461
=> Form submission installer

src/Core/CMS.php
fixes https://github.com/HoltBosse/Alba/issues/539
=> bug: properly handle redirects getting inserted when in admin

src/Core/Page.php, src/admin/controllers/widgets/views/edit/model.php, src/admin/controllers/widgets/views/edit/position_options_form.json, src/admin/controllers/widgets/views/edit/script.js, src/admin/controllers/widgets/views/edit/view.php
only show page + position picker if the widget is overrides only
warn the user if they are applying the widget to a page+position where overrides exists and it is not there
fixes https://github.com/HoltBosse/Alba/issues/548
=> widget changes

src/Core/Template.php, src/admin/controllers/pages/views/edit/script.js
fixes https://github.com/HoltBosse/Alba/issues/315
=> feat: when chosing to add overrides on page layout, convert existing widgets over

src/Fields/Rich/Rich.php
=> feat: show label if present in rich editor field

src/admin/controllers/pages/views/edit/style.css, src/admin/controllers/pages/views/edit/view.php
=> bug: fix ordering in page edit parent page picker as well as make page core fields work on mobile

src/Core/CMS.php
=> feat: turn 404 capture on by default

src/Fields/Image/Image.php, src/Fields/ImagePosition/ImagePosition.php, src/Fields/ImagePosition/style.css, src/controllers/basic_article/custom_fields.json
does what it says on the tin, some sample code (requires `$item` be a basic article)
```php
echo "
<img
src='/image/$item->og_image'
style='
object-fit: cover;
object-position: $item->og_image_position;
height: 20rem;
width: 10rem;
'
>
";
```
=> feat: add image positioning field, and add it to basic articles

src/Fields/Image/Image.php, src/Fields/Rich/Rich.php, src/Fields/Rich/style.css, src/admin/controllers/categories/views/edit/style.css, src/admin/controllers/content/views/all/view.php, src/admin/controllers/content/views/edit/style.css, src/admin/controllers/images/views/show/style.css, src/admin/controllers/redirects/views/all/view.php, src/admin/controllers/redirects/views/edit/view.php, src/admin/controllers/tags/views/edit/style.css, src/admin/controllers/users/views/default/view.php, src/admin/controllers/widgets/views/edit/style.css, src/admin/templates/clean/css/dashboard.css, src/admin/templates/clean/css/layout.css, src/admin/templates/clean/headlibraries.php, src/admin/templates/clean/index.php, src/corecontrollers/js/js/media_selector.js
implements some hacks on media management page as i didnt want to rewrite the whole image list bit part for this pr
may not be perfect for everywhere, but better than it was and everything should be usable from mobile
=> chore: make alba more mobile friendly

src/Fields/Rich/Rich.php
=> bug: save on paste when nothing else happens

src/Core/Form.php
=> feat: extend form class

src/Core/Access.php, src/Core/User.php, src/admin/controllers/users/views/default/view.php, src/admin/controllers/users/views/edit/core_user_fields.json, src/admin/controllers/users/views/edit/model.php, src/admin/templates/clean/login.php
=> feat: add functionality so that a user can be marked to have a force password change on login

src/Core/User.php, src/admin/templates/clean/login.php
=> feat: move logic from template login file into user class methods

.github/copilot-instructions.md, biome.json
=> feat: add copilot instructions and have biome honor git ignore locally to avoid running on the vendor folder

src/Core/Tag.php, src/admin/controllers/content/views/all/model.php, src/admin/controllers/content/views/edit/model.php, src/admin/controllers/plugins/views/edit/model.php, src/admin/controllers/tags/views/edit/model.php, src/admin/controllers/users/views/edit/model.php, src/admin/controllers/widgets/views/edit/model.php
does what it says on the tin. avoids error showing if you visit the links
=> bug: prevent out of bound id access

src/Fields/Rich/Rich.php, src/Fields/Rich/style.css
=> chore: convert to tiptap v3

src/Fields/Rich/Rich.php, src/corecontrollers/js/js/image_uploading.js
=> feat: add the ability to drop images on the rich editor and upload them

src/admin/controllers/users/views/edit/model.php
=> Custom user states in edit page

src/admin/templates/clean/css/darkmode.css
=> bug: dont apply some darkmode tweaks to darkmode users when the light theme is set

src/Fields/SqlSelector/SqlSelector.php
prevents needing to create a million fields for custom queries
=> feat: add sql selector field

src/Core/CMS.php, src/Core/ErrorManager.php
=> feat: handle errors being shown to users better

src/Widgets/Menu/Menu.php, src/Widgets/Menu/menu_widget_admin.js
does what it says on the tin, follow up to https://github.com/HoltBosse/Alba/pull/622
=> bug: dont put dashes in page titles when added to list

src/Fields/Rich/Rich.php
tested that this doesnt break default case. didnt test with a custom endpoint. exact same as imae field, so it should be the same
....famous last words
=> feat: support listing endpoint in rich editor

src/fakefiles/sitemap.xml.php
=> bug: only show applicable pages in sitemap on respective domains
