HoltBosse/Alba

core/fields/Field_Image.php
core/fields/Field_Repeatable.php
core/fields/Field_Select.php
core/form.php
testrepeatform.json

This should fix existing HB Gallery widget (nobody noticed that if you go back into a saved gallery you can't choose a new image, only add new ones or delete old entries.... ) and also now gives unique ids for each repeatable-aware form field both on page load/rendering AND when adding new repeatable entries.

Repeatablenewselect

---

core/db.php

allows people to set the query mode from a db class call. see https://andrew.holtbosselabs.com/db_testing for output of the test suite. additionally, this pr forward thinks so that additional options can be added in the future (use of an array for the third arg)
```php
function dbdump($title, $data) {
echo "<div style='border-bottom: 2px solid black;'>";
echo "<p>$title</p>";
CMS::pprint_r($data);
echo "</div>";
}
echo "<div style='display: flex; gap: 1rem; flex-wrap: wrap;'>";
dbdump("fetchall - no args", DB::fetchall("SELECT * FROM content WHERE 1"));
dbdump("fetchall - pdo args", DB::fetchall("SELECT * FROM content WHERE state=?", [1]));
dbdump("fetchall - pdo args, options: mode=>array", DB::fetchall("SELECT * FROM content WHERE state=?", [1], ["mode"=>PDO::FETCH_ASSOC])); …
```

feat: add ability to change mode in db class

---

.gitignore
admin/controllers/images/views/show/model.php
admin/controllers/images/views/uploadv2/model.php
core/controllers/image/controller.php
core/file.php
core/image.php

Allow fourth parameter in image controller URL for selecting format.
i.e. /image/12/800/webp
If omitted, assumes mimetype of originally saved image in db.
I know I balked at this suggestion from multiple sources originally, but, as usual, good ideas take time to settle in my brain.
Edit:
If omitted, may be nice to have a Config value to state preferred format if none given - could even ship with 'webp' as the default? Worth discussion at next LAL.

Imageformatmagic

---

.gitignore
core/cache.php
core/cms.php

Simple caching mechanism now in place. For now only used for full-page caching, but helps tremendously on pages where DB calls are a little sluggish but don't have to be immediately up-to-date. (Looking at you Starks).
Speaking of Starks - as well as being the reason I worked on this - they were used for testing too - see https://starks.holtbosselabs.com
***
Caching is only used if the $caching variable is present in _config.php_
```php
static $caching = [
"type" => "fullpage",
"time" => 15,
"ignore" => ["/contact-us"]
];
```
"type" isn't used yet - but future work will enable either module-only caching, controller-only or a combination. This would enable smaller cache files/storage, and per-entity cache times etc.
"time" - time in minutes max cache time. 
"ignore" - array of URI partial …

Pagecaching

---

core/fields/Field_Rich.php

Applies the following changes/fixes:
- Keep WYSIWYG editor and raw markup textarea in synch after each keypress OR modal operation instead of on blur. Hopefully fixes bug Josh was having repeatedly.
- If WYSIWYG modal contains an input field, it will receive focus after modal is generated.

Editortweaks

---

admin/templates/clean/js/script.js
core/fields/Field_Tab.php

see title - also done in a repeatable element friendly fashion
how to test:
checkout this pr, make sure your paganation is set to something over 100, save it
apply bobs broken commit https://github.com/HoltBosse/Alba/commit/32a4c7176ff70fb5321ecc7675d68dab56e885b3
try to save again, notice it properly switches to the tab with the error. observe no more warnings in the console about unfocusable elements.

feat: switch to tab with error if present

---

core/category.php
core/tag.php

Plugin for testing:
Folder: clear_cache_on_save
plugin_class.php
```php
<?php
defined('CMSPATH') or die; // prevent unauthorized access
class Plugin_clear_cache_on_save extends Plugin {
public function init() {
CMS::add_action("on_content_save", $this, 'clear_cache');
CMS::add_action("on_tag_save", $this, 'clear_cache');
CMS::add_action("on_category_save", $this, 'clear_cache');
}
public function clear_cache($args) {
$cache_available = property_exists('Config','caching');
if ($cache_available) {
// clear cache
$fileSystemIterator = new FilesystemIterator(CMSPATH . '/cache');
foreach ($fileSystemIterator as $file) {
unlink(CMSPATH . '/cache/'.$file->getFilename());
}
// CMS::log('Cache cleared by clear cache on save plugin');
}
else {
// CMS::log('Cache not cleared by clear cache on save …
```

init: content and tag save hooks started

---

admin/controllers/categories/views/all/view.php
admin/controllers/content/views/all/view.php

Tired of the state section/publish button in admin tables looking like this?
Me too. So now they look like this:

feat: fixes vertically uncentered state button

---

admin/controllers/pages/views/edit/view.php

no idea why a section that has no controls for open and closing has css for it. anyways, fixes issue where content would overflow because the open css was limiting instead of allowing to autoflow. also adds a width so its easier to use fields

bug: fix bobs css

---

configTESTBACKUP.php
installer/index.php

Fixes #267. Basically static code required in config by CMS will now be added when the config is re-created by /installer/index.php. Also cleans up formatting.

fix: installer error __callStatic function not copied into new config

---

core/fields/Field_Repeatable.php

see title. since the old line wasnt proper regex, it wasnt actually replacing anything. however when the page was reloaded, the php based indexing was kicking in, making it work on the second save
TLDR: repeatable's are driving me insane

bug: make repeatable indexed fields work properly with proper regex

---

core/fields/Field_Select.php

what it says on the tin
test code(core controller):
```php
<?php 
if(CMS::Instance()->uri_segments[1] && CMS::Instance()->uri_segments[1]=="api") {
header('Content-Type: application/json; charset=utf-8');
echo json_encode(["data"=>[
(object)["text"=>$_GET["searchterm"] . "_" . uniqid(), "value"=>uniqid()],
(object)["text"=>$_GET["searchterm"] . "_" . uniqid(), "value"=>uniqid()]
]]);
die;
}
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.27.1/slimselect.min.js"></script>';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.27.1/slimselect.min.css" rel="stylesheet">';
$form = new Form((object) [
"id"=> "select_testing",
"fields"=>[
(object) [
"name" => "models",
"id" => "models",
"type" => "Select",
"label" => "Select Stuff",
"slimselect" => …
```

feat: add option for select field to use ajax

---

admin/controllers/categories/views/edit/model.php
admin/controllers/content/views/edit/model.php
admin/controllers/images/views/edit/model.php
admin/controllers/tags/views/edit/model.php
core/category.php
core/content.php
core/tag.php

Rectifying a silly historic decision to have various save functions be responsible for redirection/messaging instead of simply returning a boolean (and logging where necessary) and doing stuff after being called where appropriate.
This allows these functions to work better when called from front-end / non-core code.

Bettercontentsave

---

core/cms.php

move cache serving checks to post-session creation to allow further checks before serving cached pages
also adjust cache creation to avoid any cache when user logged in to avoid security issues

init: safer caching

---

admin/controllers/content/views/all/view.php
admin/controllers/users/views/default/view.php

what the title says
if you want to enable the feature, `static $show_ids_in_tables = true;` has to be added to admin_config.php*warning, tracked in alba file

feat: add the config option to show ids in tables

---

core/fields/Field_Select.php

empty_string is variable used in at least one 'select' child class (contentselector) to display an option with a 0 value at the top of a dropdown

fix: Contentselector maybe others with empty_string

---

core/cms.php
core/fields/Field_Rich.php
core/fields/Field_Tab.php
core/hook.php
phpstan.neon

the first ignore rule is due to our use of __callstatic in the config file, probably fixable in the long term with some phpdoc comments or something
the second is due to variables not being defined in the current file

phpstan level 1

---

core/controllers/image/controller.php
phpstan.neon

probably should do something about deduplicating the make_thumb function at some point since its duplicated across three different places

feat: enable testing for image core controller and fix duplicate function

---

core/fields/Field_Rich.php

make it more obvious when the editor is invalid

---

admin/controllers/categories/views/action/model.php
admin/controllers/categories/views/edit/model.php
admin/controllers/content/views/action/model.php
admin/controllers/content/views/all/view.php
admin/controllers/content/views/edit/model.php
admin/controllers/pages/views/action/model.php
admin/controllers/pages/views/save/model.php
admin/controllers/plugins/views/action/model.php
admin/controllers/redirects/views/action/model.php
admin/controllers/redirects/views/all/view.php
admin/controllers/tags/views/action/model.php
admin/controllers/tags/views/edit/model.php
admin/controllers/users/views/action/model.php
admin/controllers/users/views/save/model.php
admin/controllers/widgets/views/action/model.php
admin/controllers/widgets/views/edit/view.php
core/plugin.php
core/widget.php
plugins/core_frontend_editbutton/plugin_class.php

- When saving content items, widgets, pages, users, tags, etc, it returns to the previous page. 
- Success messages now contain a link back to the edited item.

Better save

---

core/cms.php

Before storing redirect/404 in table, check it isn't:
- A request for a file suffix we don't care about (e.g. zip, bz, etc)
- Or a wordpress drive-by attempt

feat: redirect noise storage removal

---

core/actions.php
core/actions/Action_userlogin.php
core/cms.php

pr does two things
* fixes and issue where the audit log would show `()` if there was no user, which is bad for audit actions done by unlogged in users, such as on a front end (there is a hack that shows this same unknown value on a certain site)
* adds audit log tracking of users that log in

Userloginaudit

---

admin/controllers/content/views/edit/model.php

does what it says on the tin.
thought about allowing hooking form class itself, but decided on this for now

feat: add hook position to allow overriding default fields in content form

---

admin/controllers/pages/page_options.json
core/form.php

was digging around in pages, figuring out exactly how they worked, and found fields with "error!!!" in them, so fixed that

bug: make serialization honor save param, apply save field to page options

---

admin/controllers/users/views/default/view.php
core/users_search.php

does what it says on the tin.
only tested three of the five, but should all be good.
sample plugin that allows searching users by id:
```php
class Plugin_user_admin_search extends Plugin {
public function init() {
CMS::add_action("render_custom_user_search_filters",$this,'user_render_search_fields'); // label, function, priority
CMS::add_action("custom_user_search_where",$this,'user_handle_search_where'); // label, function, priority
CMS::add_action("custom_user_search_params",$this,'user_handle_search_params'); // label, function, priority  
}
public function user_render_search_fields ($args) {
?>
<div class="field">
<label class="label">Search id</label>
<div class="control">
<input style="max-width: 10rem;" value="<?php echo $_GET["id"]; ?>" name="id" form="searchform" class="input" …
```

feat: add the same hooks as content search for user search

---

core/content_search.php

bug existed since flat - can potentially return ids of current content type that are not tagged if there's a collision with an id of another content_type that _is_ tagged

bug: fix tag query in content_search

---

core/fields/Field_Image.php

see title,
requires:
* using `listing_endpoint` and changing the `filter`
* httpapi following current schema, with an extra `imageurl` param
* hiding crop and upload new image via css ...... or otherwise overriding them

feat: allow the image field to be used with custom non cms urls

---

core/component.php

chore: fix warning in navigation so that you can actually use it when warning spam is on

---

core/fields/Field_Textarea.php

Remove redundant 'value' attribute from textarea that caused errors with special characters.

fix: remove redundant 'value' attribute from textarea

---

admin/controllers/categories/views/edit/model.php
admin/controllers/content/views/check/model.php
admin/controllers/content/views/edit/model.php
admin/controllers/images/views/edit/model.php
admin/controllers/pages/views/edit/model.php
admin/controllers/pages/views/save/model.php
admin/controllers/redirects/views/edit/model.php
admin/controllers/tags/views/edit/model.php
core/access.php
core/cms.php
core/component.php
core/content.php
core/fields/Field_Parsedown.php
core/widget.php
index.php
plugins/core_frontend_editbutton/plugin_class.php

NOTES:
* removes ADMINPATH from index.php
* reduces our `// @phpstan-ignore-next-line` count to 5 lines
* gets rid of 15 instances of `// @phpstan-ignore-next-line`
* our two ignore errors remain unchanged

chore: change up usage of adminpath to avoid death by warnings

---

admin/controllers/audit/views/default/style.css
admin/controllers/audit/views/default/view.php
admin/controllers/categories/views/all/style.css
admin/controllers/categories/views/all/view.php
admin/controllers/categories/views/edit/view.php
admin/controllers/content/views/all/style.css
admin/controllers/content/views/all/view.php
admin/controllers/forms/views/submissions/view.php
admin/controllers/pages/views/default/view.php
admin/controllers/plugins/views/show/view.php
admin/controllers/redirects/views/all/style.css
admin/controllers/redirects/views/all/view.php
admin/controllers/settings/views/backups/view.php
admin/controllers/settings/views/general/view.php
admin/controllers/settings/views/info/view.php
admin/controllers/settings/views/updates/view.php
admin/controllers/tags/views/show/view.php
admin/controllers/users/views/default/style.css
admin/controllers/users/views/default/view.php
admin/controllers/widgets/views/show/style.css
admin/controllers/widgets/views/show/view.php
admin/templates/clean/css/layout.css
admin/templates/clean/navigation.php
core/component.php
core/js/admin_row.js

does the following
* create component for headers, ditch h1 as container, flex nicely on mobile, and make all pages use it
* create component toolbar for publish/delete/etc
* move toolbar to below search so that forms could be done sanely rather than fields bound to empty forms above, etc
* fix categories so that rows could be selected to publish/delete/etc
* fix categories editing so it had a cancel button and matches the rest of the cms in editing experience

admin header refactoring and unification

---

admin/templates/clean/css/darkmode.css
admin/templates/clean/css/dashboard.css

- updated calendar selector icon to be visible in dark mode and adjusted it to be at the end of the input box (for `date`, `time`, `datetime-local`, `week`, and `month`)
- made the slim selector border consistent with the other input borders

input field css updates

---

core/category.php
core/cms.php
core/content.php
core/content_search.php
core/controller.php
core/db.php
core/form.php
core/image.php
core/json.php
core/mail.php
core/messages.php
core/plugin.php
core/template.php
core/user.php

if debug is of, shows cms error to the user, if its on, shows this:
see https://www.php.net/manual/en/function.set-exception-handler.php regard exception handling. the tldr is this allows us to try/catch cms methods (handler doesnt fire), and if we dont have a try/catch the handler will kick in display the exception according to the configs debug flag

feat: convert core cms files to use exceptions rather than errors and add exceptions handler

---

src/Fields/Rich/Rich.php
src/Fields/Rich/figcaption.js
src/Fields/Rich/figure.js
src/Fields/Rich/style.css

disclaimer: played a bit with vibe coding on the ability for figcaption to have enter out of figure on second enter of a blank paragraph to follow details, quote, etc elements - yes the code for it is terrible. it does work. yes the schema and state logic keeps is somewhat in bounds
i do hope that tiptap one day adds a extension themselves for figures, however the current experiments havent been updated in like 2-4 years

figures support in the editor

---

src/Fields/TagSingle/TagSingle.php

seems this got removed at some point

chore: add support back? for string content types in tag fields

---

bin/datafiles/.htaccess

bug: update default htaccess to only block /vendor from the start of the url to avoid touching other url segments that have vendor in it
